name: Release with Tag (v*.*.*) & Push Nuget
on:
  push:
    tags:
    - "Validation.v*.*.*"
    - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    #- name: Verify commit exists in origin/master
    #  run: |
    #    git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    #    git branch --remote --contains | grep origin/master
       
    - name: Set VERSION variable from tag
      run: | 
            echo "VERSION=${GITHUB_REF#refs/tags/Validate.v}"
          
    - name: Check output
      run: |
          echo ${VERSION}
     
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    #- name: Test
    #  run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    #- name: Pack
    #  run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
    #- name: Push
    #  run: dotnet nuget push "*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
    #  env:
    #    NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
